name: Deploy perlite blog

on:
  push:
    branches:
      - "main"

  workflow_dispatch:

concurrency:
  group: "perlite"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Update blog on server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: bash ~/blog/update-blog.sh
